# --- Performance & Behavior ---
gpu-api=vulkan
hwdec=auto
save-position-on-quit=yes

# --- Aesthetic (The Rice) ---
osc=no                                  # Disable default UI (Required for ModernZ)
border=no                               # No title bar
osd-font='Monocraft'
osd-font-size=30
osd-color='##dbf4ff'
osd-border-color='##000000'
osd-border-size=2

# --- Subtitles (Matching your TUI vibe) ---
sub-font='Monocraft'
sub-font-size=40
sub-color='##dbf4ff'
sub-border-color='##000000'
sub-border-size=2
