[config]
version_check = false
fallback_color = "#ffbf9b"
prefer = "closest-to-fallback"
caching = false
expr_prefix = "{{"
expr_postfix = "}}"
block_prefix = "<*"
block_postfix = "*>"
contrast = 1.0
source_color_index = 1

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[config.custom_colors]
red = "#ff0000"
blue = "#0000ff"
green = "#00ff00"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/current-theme.conf"
post_hook = "pkill -USR1 kitty"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/hyprland.lua"
post_hook = "hyprctl reload"
