"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#dbf4ff)\
$os\
$username\
[](bg:#dcf4fe fg:#dbf4ff)\
$directory\
[](fg:#dcf4fe bg:#f0eeff)\
$git_branch\
$git_status\
[](fg:#f0eeff bg:#b6eaff)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#b6eaff bg:#cfe6f0)\
$docker_context\
[](fg:#cfe6f0 bg:#e0e0ff)\
$time\
[ ](fg:#e0e0ff)\
"""

[username]
show_always = true
style_user = "bg:#dbf4ff fg:#000000"
style_root = "bg:#dbf4ff fg:#000000"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#dbf4ff fg:#000000"
disabled = true

[directory]
style = "bg:#dcf4fe fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#cfe6f0 fg:#000000"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#f0eeff fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f0eeff fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#b6eaff fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#e0e0ff fg:#000000"
format = '[ ♥ $time ]($style)'
