# --- Performance & Behavior ---
gpu-api=vulkan
hwdec=auto
save-position-on-quit=yes

# --- Aesthetic (The Rice) ---
osc=no                                  # Disable default UI (Required for ModernZ)
border=no                               # No title bar
osd-font='Monocraft'
osd-font-size=30
osd-color='#{{colors.primary.default.hex}}'
osd-border-color='#{{colors.surface_container_lowest.default.hex}}'
osd-border-size=2

# --- Subtitles (Matching your TUI vibe) ---
sub-font='Monocraft'
sub-font-size=40
sub-color='#{{colors.primary.default.hex}}'
sub-border-color='#{{colors.surface_container_lowest.default.hex}}'
sub-border-size=2
