"$schema" = 'https://starship.rs/config-schema.json'

format = """
[]({{colors.primary.default.hex}})\
$os\
$username\
[](bg:{{colors.secondary.default.hex}} fg:{{colors.primary.default.hex}})\
$directory\
[](fg:{{colors.secondary.default.hex}} bg:{{colors.tertiary.default.hex}})\
$git_branch\
$git_status\
[](fg:{{colors.tertiary.default.hex}} bg:{{colors.primary_fixed.default.hex}})\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:{{colors.primary_fixed.default.hex}} bg:{{colors.secondary_fixed.default.hex}})\
$docker_context\
[](fg:{{colors.secondary_fixed.default.hex}} bg:{{colors.tertiary_fixed.default.hex}})\
$time\
[ ](fg:{{colors.tertiary_fixed.default.hex}})\
"""

[username]
show_always = true
style_user = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
style_root = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
disabled = true

[directory]
style = "bg:{{colors.secondary.default.hex}} fg:{{colors.on_secondary.default.hex}}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:{{colors.secondary_fixed.default.hex}} fg:{{colors.on_secondary_fixed.default.hex}}"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:{{colors.tertiary.default.hex}} fg:{{colors.on_tertiary.default.hex}}"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:{{colors.tertiary.default.hex}} fg:{{colors.on_tertiary.default.hex}}"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:{{colors.primary_fixed.default.hex}} fg:{{colors.on_primary_fixed.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:{{colors.tertiary_fixed.default.hex}} fg:{{colors.on_tertiary_fixed.default.hex}}"
format = '[ ♥ $time ]($style)'
