[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.append_keymap]]
on = "q"
run = "plugin autosession --save-and-quit"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin wl-clipboard"]
desc = "Copy to clipboard"
