# The basic colors
foreground              #ffffff
# Using 'surface' instead of 'lowest' for a slightly better dark grey
background              #191114
selection_foreground    #000000
selection_background    #ffebf1

# Cursor colors
cursor                  #ffebf1
cursor_text_color       #000000

# URL color
url_color               #ffece3

# Tab bar
active_tab_foreground   #000000
active_tab_background   #ffebf1
inactive_tab_foreground #ffffff
inactive_tab_background #4e4448

# The 16 terminal colors (Vibrant Version)

# black
color0  #42393c
color8  #ffebf1

# red (Standardizing these for better visibility)
color1  #ffece9
color9  #ffaea4

# green
color2  #ffebf1
color10 #f9accf

# yellow
color3  #ffece3
color11 #eeb795

# blue
color4  #ffebf1
color12 #dcb9c7

# magenta
color5  #ffd8e7
color13 #feb0d3

# cyan
color6  #fed9e7
color14 #e0bdcb

# white
color7  #ffffff
color15 #ffffff
