# The basic colors
foreground              #ffffff
# Using 'surface' instead of 'lowest' for a slightly better dark grey
background              #0f1416
selection_foreground    #000000
selection_background    #dcf4fe

# Cursor colors
cursor                  #dbf4ff
cursor_text_color       #000000

# URL color
url_color               #f0eeff

# Tab bar
active_tab_foreground   #000000
active_tab_background   #dbf4ff
inactive_tab_foreground #ffffff
inactive_tab_background #42484a

# The 16 terminal colors (Vibrant Version)

# black
color0  #373c3f
color8  #e9f1f6

# red (Standardizing these for better visibility)
color1  #ffece9
color9  #ffaea4

# green
color2  #dbf4ff
color10 #84cde7

# yellow
color3  #f0eeff
color11 #bfbfe7

# blue
color4  #dcf4fe
color12 #afc6d0

# magenta
color5  #b6eaff
color13 #87d1eb

# cyan
color6  #cfe6f0
color14 #b3cad4

# white
color7  #ffffff
color15 #ffffff
