# The basic colors
foreground              #ffffff
# Using 'surface' instead of 'lowest' for a slightly better dark grey
background              #14140c
selection_foreground    #000000
selection_background    #f4f2cc

# Cursor colors
cursor                  #f4f59c
cursor_text_color       #000000

# URL color
url_color               #ccfae6

# Tab bar
active_tab_foreground   #000000
active_tab_background   #f4f59c
inactive_tab_foreground #ffffff
inactive_tab_background #48473e

# The 16 terminal colors (Vibrant Version)

# black
color0  #3c3c33
color8  #f3f0de

# red (Standardizing these for better visibility)
color1  #ffece9
color9  #ffaea4

# green
color2  #f4f59c
color10 #c6c773

# yellow
color3  #ccfae6
color11 #a0ccba

# blue
color4  #f4f2cc
color12 #c6c4a1

# magenta
color5  #e6e790
color13 #cacb77

# cyan
color6  #e6e4bf
color14 #cac8a5

# white
color7  #ffffff
color15 #ffffff
