# ==============================================================================
#                        HYPRLOCK CUSTOM CONFIGURATION
#                  Location: ~/.config/hypr/hyprlock.conf
# ==============================================================================

general {
    hide_cursor = true          # Hides mouse cursor when locked
    disable_loading_bar = true  # Lean startup
}

background {
    monitor =
    # Choice 1: Blur your live desktop behind the lock screen (Very Modern Hacker)
    path = screenshot
    blur_passes = 3
    blur_size = 5

    # Choice 2: Or override with a flat dark hex color block if you want it pure text
    color = rgb(17, 19, 27)
}

# --- SYSTEM DIGITAL CLOCK ---
label {
    monitor =
    text = $TIME
    color = rgb(255, 255, 255)
    font_size = 85
    font_family = Monocraft

    position = 0, 150
    halign = center
    valign = center
}

# --- THE INPUT FIELD ---
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 3

    font_family = Monocraft

    rounding = 0
    outer_color = rgb(122, 162, 247)
    inner_color = rgb(26, 27, 38)
    font_color = rgb(200, 215, 245)


    # Dots Formatting
    dots_size = 0.3
    dots_spacing = 0.25
    dots_center = true

    # Placeholder & Text Overlays
    fade_on_empty = false
    placeholder_text = <i><span foreground="##7aa2f7">Enter Password...</span></i>
    hide_input = false

    # State Flashing Changes
    check_color = rgb(224, 175, 104) # Yellow tint when verifying
    fail_color = rgb(247, 118, 118)  # Sharp Red tint if bad pass
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    position = 0, -40
    halign = center
    valign = center
}
